### ISSUE TITLE
Ability to makeChild/clone/fork a forge

### ISSUE THREAD

**Issue by Rush** [nkohari/forge#2]
I would like to have this function to create scoped dependencies that will be changed for a different set of dependencies with the same name. I would hate to use `unbind` for this.

PS. Very nice project. Clean, well documented and does not constrain the user unlike other DI frameworks like angular/di.js

**Comment by nkohari** [comment]
Yeah, `unbind()` is a very blunt object. :) I like the idea of being able to make a copy of a forge. Something like:

``` coffeescript
forge = new Forge()
forge.bind('foo').to.type(Foo)

anotherForge = forge.clone()
anotherForge.bind('bar').to.type(Bar)
# anotherForge now has bindings for foo and bar
```

I'm not sure how difficult it would be to clone the bindings, but I can take a look at it.

**Comment by Rush** [comment]
The above looks good, looking forward to it! Basically I will use it before starting several  asynchronous actions. Each of them will get the cloned forge and handle dependencies separately from the rest from that point.

**Comment by Rush** [comment]
Just wanted to know whether I should make a workaround until this feature is complete? (read: do you intend to work on this in the next couple of days?) Alternatively if this is easy to do I could perhaps implement it and make a pull request, I am not very versatile in CoffeeScript though.

**Comment by nkohari** [comment]
Sorry, I can't guarantee I'll get to it within the next couple of days -- the cloning is definitely possible but might be a little tricky. Will definitely look into it soon, though.
